In [44]:
import json

fname = '/data1/kaggle/Korean_DCS_2024/data/일상대화요약_train.json'

with open(fname, "r") as f:
    data = json.load(f)

for row in data:
    subject_keywords = row['input']['subject_keyword']
    subject_keywords = ', '.join(subject_keywords)
    output = row['output']
    conv_df = pd.DataFrame(row['input']['conversation'])
    chat_data = preprocess_chat(conv_df)
    break

In [46]:
chat_data

'\n\n SD2000001 : 저는 여행 다니는 것을 굉장히 좋아하는데요. 그래가지고 스페인이나 뭐 영국 유럽 아니면 국내에서도 뭐 강릉이나 전주 같은 데를 많이 다녔는데 혹시 여행 다니는 거 좋아하시나요?\n\n SD2000002 : 저 여행 다니는 거 되게 좋아해서 대학교 내내 여행을 엄청 많이 다녔었는데요. 제가 고등학교 때는 여행에 대해 흥미가 없었는데 그게 좀 아버지가 짠대로 패키지처럼 여행을 다녀서 그런 것 같아요. 그래서 대학교 간 이후로는 해외여행을 되게 많이 갔었는데 그중에서 제일 기 좋았던 거는 스페인이랑 포르투갈이었거든요. 어~ 혹시 포르투갈이나 스페인 유럽 쪽 다녀오신 적 있으신가요?\n\n SD2000001 : 어~ 네. 저도 우연히 스페인과 포르투갈을 다녀왔었었습니다. 어~ 저는 스페인 중에서도 마드리드에 근교에 있었던 톨레도라는 지역이 굉장히 좋았는데요. 그 톨레도에서 특히 기억에 남았던 거는 거기에 대성당이 있는데 그 성당이 엄청 화려하더라고요. 그래서 거기를 꾸며논 거를 보면은 금을 엄청 많이 사용해가지고 되게 빤짝빤짝하고 좀 성당은 보통 좀 소박하다라는 인식이 있었는데 아~ 이렇게 화려한 성당도 있구나라는 거를 새롭게 알게 됐었습니다. 어~ 또 톨레도에 지역 음식도 같이 먹었었는데 아~ 이름은 지금 잘 생각이 나지는 않지만 굉장히 달달했던 그런 디저트 종류였는데 그~ 디저트도 먹고 그다음에 천천히 걸어 다니면서 주변 풍경도 보고 근교 여행만의 약간 소박한 맛이 있었다고 생각을 합니다. 어~ 또 물론 마드리드도 굉장히 좋았는데 유럽 여행을 많이 가셨다고 해서 혹시 톨레도도 가본 적이 있나요?\n\n SD2000002 : 아~ 제가 톨레도도 다녀왔는데 저는 이제 여행 일정을 길게 잡아서 톨레도는 하루를 봤는데 도 그렇게 너무 더웠기 때문에 많이 보진 못한 것 같아요. 그때는 버스 관광버스를 타고 계속 돌아다니면서 이제 내리는 데마다 관광을 할 수 있는 버스를 탔는데요. 그 버스를 타고 전체를 다 내려서 보려고 했지만 날씨가 너무 더워서 금방 금방 이제 xx 장소로 넘어갔던 것 같 같습니다. 거기는 이제 고대 도시라고 해서 사람들이 많이 추천한 거에 비해서는 저는 하루를 잡기에는 조금 부족한 여행지라는 생각이 들었고 오히려 광장에서 쇼핑을 했던 게 더 기억에 남습니다.'

In [29]:
', '.join(data[-1]['input']['subject_keyword'])

'맛집'

In [31]:
import pandas as pd

conversation = data[0]['input']['conversation']
conv_df = pd.DataFrame(conversation)

In [42]:
def preprocess_chat(conv_df:pd.DataFrame) -> str:

    result = []
    past_speaker = None
    for _, row in conv_df.iterrows():
        if past_speaker == row['speaker']:
            result += [' ' + row['utterance']]
        else:
            result += [f"\n\n {row['speaker']} : {row['utterance']}"]
            past_speaker = row['speaker']

    xdata = ''.join(result)
    return xdata

In [43]:
preprocess_chat(conv_df)

'\n\n SD2000001 : 저는 여행 다니는 것을 굉장히 좋아하는데요. 그래가지고 스페인이나 뭐 영국 유럽 아니면 국내에서도 뭐 강릉이나 전주 같은 데를 많이 다녔는데 혹시 여행 다니는 거 좋아하시나요?\n\n SD2000002 : 저 여행 다니는 거 되게 좋아해서 대학교 내내 여행을 엄청 많이 다녔었는데요. 제가 고등학교 때는 여행에 대해 흥미가 없었는데 그게 좀 아버지가 짠대로 패키지처럼 여행을 다녀서 그런 것 같아요. 그래서 대학교 간 이후로는 해외여행을 되게 많이 갔었는데 그중에서 제일 기 좋았던 거는 스페인이랑 포르투갈이었거든요. 어~ 혹시 포르투갈이나 스페인 유럽 쪽 다녀오신 적 있으신가요?\n\n SD2000001 : 어~ 네. 저도 우연히 스페인과 포르투갈을 다녀왔었었습니다. 어~ 저는 스페인 중에서도 마드리드에 근교에 있었던 톨레도라는 지역이 굉장히 좋았는데요. 그 톨레도에서 특히 기억에 남았던 거는 거기에 대성당이 있는데 그 성당이 엄청 화려하더라고요. 그래서 거기를 꾸며논 거를 보면은 금을 엄청 많이 사용해가지고 되게 빤짝빤짝하고 좀 성당은 보통 좀 소박하다라는 인식이 있었는데 아~ 이렇게 화려한 성당도 있구나라는 거를 새롭게 알게 됐었습니다. 어~ 또 톨레도에 지역 음식도 같이 먹었었는데 아~ 이름은 지금 잘 생각이 나지는 않지만 굉장히 달달했던 그런 디저트 종류였는데 그~ 디저트도 먹고 그다음에 천천히 걸어 다니면서 주변 풍경도 보고 근교 여행만의 약간 소박한 맛이 있었다고 생각을 합니다. 어~ 또 물론 마드리드도 굉장히 좋았는데 유럽 여행을 많이 가셨다고 해서 혹시 톨레도도 가본 적이 있나요?\n\n SD2000002 : 아~ 제가 톨레도도 다녀왔는데 저는 이제 여행 일정을 길게 잡아서 톨레도는 하루를 봤는데 도 그렇게 너무 더웠기 때문에 많이 보진 못한 것 같아요. 그때는 버스 관광버스를 타고 계속 돌아다니면서 이제 내리는 데마다 관광을 할 수 있는 버스를 탔는데요. 그 버스를 타고 전체를 다 내려서 보려고 했지만 날씨가 너무 더워서 금방 금방 이제 xx 장소로 넘어갔던 것 같 같습니다. 거기는 이제 고대 도시라고 해서 사람들이 많이 추천한 거에 비해서는 저는 하루를 잡기에는 조금 부족한 여행지라는 생각이 들었고 오히려 광장에서 쇼핑을 했던 게 더 기억에 남습니다.'

In [41]:
''.join(result)

'\n\n SD2000001 : 저는 여행 다니는 것을 굉장히 좋아하는데요. 그래가지고 스페인이나 뭐 영국 유럽 아니면 국내에서도 뭐 강릉이나 전주 같은 데를 많이 다녔는데 혹시 여행 다니는 거 좋아하시나요?\n\n SD2000002 : 저 여행 다니는 거 되게 좋아해서 대학교 내내 여행을 엄청 많이 다녔었는데요. 제가 고등학교 때는 여행에 대해 흥미가 없었는데 그게 좀 아버지가 짠대로 패키지처럼 여행을 다녀서 그런 것 같아요. 그래서 대학교 간 이후로는 해외여행을 되게 많이 갔었는데 그중에서 제일 기 좋았던 거는 스페인이랑 포르투갈이었거든요. 어~ 혹시 포르투갈이나 스페인 유럽 쪽 다녀오신 적 있으신가요?\n\n SD2000001 : 어~ 네. 저도 우연히 스페인과 포르투갈을 다녀왔었었습니다. 어~ 저는 스페인 중에서도 마드리드에 근교에 있었던 톨레도라는 지역이 굉장히 좋았는데요. 그 톨레도에서 특히 기억에 남았던 거는 거기에 대성당이 있는데 그 성당이 엄청 화려하더라고요. 그래서 거기를 꾸며논 거를 보면은 금을 엄청 많이 사용해가지고 되게 빤짝빤짝하고 좀 성당은 보통 좀 소박하다라는 인식이 있었는데 아~ 이렇게 화려한 성당도 있구나라는 거를 새롭게 알게 됐었습니다. 어~ 또 톨레도에 지역 음식도 같이 먹었었는데 아~ 이름은 지금 잘 생각이 나지는 않지만 굉장히 달달했던 그런 디저트 종류였는데 그~ 디저트도 먹고 그다음에 천천히 걸어 다니면서 주변 풍경도 보고 근교 여행만의 약간 소박한 맛이 있었다고 생각을 합니다. 어~ 또 물론 마드리드도 굉장히 좋았는데 유럽 여행을 많이 가셨다고 해서 혹시 톨레도도 가본 적이 있나요?\n\n SD2000002 : 아~ 제가 톨레도도 다녀왔는데 저는 이제 여행 일정을 길게 잡아서 톨레도는 하루를 봤는데 도 그렇게 너무 더웠기 때문에 많이 보진 못한 것 같아요. 그때는 버스 관광버스를 타고 계속 돌아다니면서 이제 내리는 데마다 관광을 할 수 있는 버스를 탔는데요. 그 버스를 타고 전체를 다 내려서 보려고 했지만 날씨가 너무 더워서 금방 금방 이제 xx 장소로 넘어갔던 것 같 같습니다. 거기는 이제 고대 도시라고 해서 사람들이 많이 추천한 거에 비해서는 저는 하루를 잡기에는 조금 부족한 여행지라는 생각이 들었고 오히려 광장에서 쇼핑을 했던 게 더 기억에 남습니다.'

In [47]:
row

{'id': 'nikluge-2024-일상 대화 요약-train-000001',
 'input': {'conversation': [{'speaker': 'SD2000001',
    'utterance': '저는 여행 다니는 것을 굉장히 좋아하는데요. 그래가지고 스페인이나 뭐 영국 유럽 아니면 국내에서도 뭐 강릉이나 전주 같은 데를 많이 다녔는데'},
   {'speaker': 'SD2000001', 'utterance': '혹시 여행 다니는 거 좋아하시나요?'},
   {'speaker': 'SD2000002',
    'utterance': '저 여행 다니는 거 되게 좋아해서 대학교 내내 여행을 엄청 많이 다녔었는데요.'},
   {'speaker': 'SD2000002',
    'utterance': '제가 고등학교 때는 여행에 대해 흥미가 없었는데 그게 좀 아버지가 짠대로 패키지처럼 여행을 다녀서 그런 것 같아요.'},
   {'speaker': 'SD2000002',
    'utterance': '그래서 대학교 간 이후로는 해외여행을 되게 많이 갔었는데 그중에서 제일 기 좋았던 거는 스페인이랑 포르투갈이었거든요.'},
   {'speaker': 'SD2000002',
    'utterance': '어~ 혹시 포르투갈이나 스페인 유럽 쪽 다녀오신 적 있으신가요?'},
   {'speaker': 'SD2000001', 'utterance': '어~ 네. 저도 우연히 스페인과 포르투갈을 다녀왔었었습니다.'},
   {'speaker': 'SD2000001',
    'utterance': '어~ 저는 스페인 중에서도 마드리드에 근교에 있었던 톨레도라는 지역이 굉장히 좋았는데요. 그 톨레도에서 특히 기억에 남았던 거는 거기에 대성당이 있는데 그 성당이 엄청 화려하더라고요. 그래서 거기를 꾸며논 거를 보면은 금을 엄청 많이 사용해가지고 되게 빤짝빤짝하고 좀 성당은 보통 좀 소박하다라는 인식이 있었는데 아~ 이렇게 화려한 성당도 있구나라는 거를 새롭게 알게 됐었습니다.'},
   {'speaker': 'SD2000001',
    'utterance': '어~ 또 톨레도에 지역 음식도 같이 먹었었는데 아~ 이름은 지금 잘 생각이 나지는 않지만 굉장히 달달했던 그런 디저트 종류였는데 그~ 디저트도 먹고 그다음에 천천히 걸어 다니면서 주변 풍경도 보고 근교 여행만의 약간 소박한 맛이 있었다고 생각을 합니다.'},
   {'speaker': 'SD2000001',
    'utterance': '어~ 또 물론 마드리드도 굉장히 좋았는데 유럽 여행을 많이 가셨다고 해서 혹시 톨레도도 가본 적이 있나요?'},
   {'speaker': 'SD2000002',
    'utterance': '아~ 제가 톨레도도 다녀왔는데 저는 이제 여행 일정을 길게 잡아서 톨레도는 하루를 봤는데 도 그렇게 너무 더웠기 때문에 많이 보진 못한 것 같아요.'},
   {'speaker': 'SD2000002',
    'utterance': '그때는 버스 관광버스를 타고 계속 돌아다니면서 이제 내리는 데마다 관광을 할 수 있는 버스를 탔는데요. 그 버스를 타고 전체를 다 내려서 보려고 했지만 날씨가 너무 더워서 금방 금방 이제 xx 장소로 넘어갔던 것 같 같습니다.'},
   {'speaker': 'SD2000002',
    'utterance': '거기는 이제 고대 도시라고 해서 사람들이 많이 추천한 거에 비해서는 저는 하루를 잡기에는 조금 부족한 여행지라는 생각이 들었고'},
   {'speaker': 'SD2000002', 'utterance': '오히려 광장에서 쇼핑을 했던 게 더 기억에 남습니다.'}],
  'subject_keyword': ['해외여행']},
 'output': '이 대화에서 화자들은 좋았던 여행지와 기억나는 주요 명소에 대해 이야기했습니다. SD2000001은 여행을 좋아하여 국내, 해외 여행을 많이 다녔다고 말했습니다. 특히 기억에 남는 여행지로 스페인 마드리드의 톨레도를 소개했습니다. 그 중 화려하게 꾸며진 대성당과 디저트가 인상적이었다고 이야기했습니다. SD2000002는 대학교에 진학한 후 해외여행을 자주 다녔고, 스페인과 포루투갈이 가장 기억에 남는 여행지라고 말했습니다. 그리고 톨레도도 다녀왔지만 날씨가 더워서 제대로 구경하지 못했다는 경험을 이야기했습니다.'}

In [54]:
s1, s2 = conv_df['speaker'].unique()

In [55]:
s1

'SD2000002'

In [51]:
conv_df

      speaker                                          utterance
0   SD2000002  여행 다닐 때 저는 쇼핑 같이 물건을 사는 걸 되게 좋아하는데 여행을 다니면서 어떤...
1   SD2000001  아~ 제 여행 스타일은 어~ 너무 일정이 촘촘하지도 않고 너무 느슨하지도 않게 하루...
2   SD2000001  어~ 그리고 쇼핑에 대해서 말씀을 하셨는데 어~ 저는 사실 여행을 다니면서 쇼핑을 ...
3   SD2000001  그냥 소소하게 제가 평소에 많이 모으던 어~ 지역별로 제가 갔던 지역이나 조금 인상...
4   SD2000001  그 이외에 어~ 지역에 가서 뭔가 쇼핑을 많이 하시는 분들 같은 경우에는 특히 해외...
5   SD2000001  어~ 또 너무 또 하루에 많이 여행을 다니게 되면은 다리가 너무 많이 아프고 해서 ...
6   SD2000001  주로 중간중간에 성당에 많이 들려서 성당은 무료로 입장하는 경우가 많기 때문에 중간...
7   SD2000001  어~ 여행 스타일에 대해서 이야기를 조금 했었는데 혹시 여행 갈 때 숙소는 어떻게 ...
8   SD2000002  전 저는 숙소는 보통 같이 가는 사람들한테 많이 맞추는 편인데요. 어~ 저는 깨끗한...
9   SD2000002  그~ 숙소는 저는 돌아다니는 걸 좋아해서 밤에 잠자는 용도로만 사용하는 경우가 되게...
10  SD2000002  그래서 그렇 유럽 같은 경우에는 벌레가 나오지 않는 것을 많이 신경 썼고요. 그리고...
11  SD2000002      그리고 깔끔한 걸 중요하게 생각하긴 하지만 아주 비싼 숙소는 선호하지 않는 편인데
12  SD2000002  제가 되게 좋은 숙소에도 많이 묵어봤는데 숙소에 있는 시간이 너무 적 적다 보니깐 ...
13  SD2000002  그리고 같이 가는 사람에 따라서 숙소 취향이 좀 많이 바뀌는 편인데 name 씨는 ...
14  SD2000001        아~ 저는 혼자 가는 여행보다는 이제 같이 가는 여행을 더 좋아하는 편입니다.
15  SD2000001  혼자 여행을 갔을 때는 어~ 혼자 뭘 해야 할지 잘 모르겠기도 하고 어~ 같이 다닐...
16  SD2000001  그리고 또 숙소에서 이제 여행을 끝나고 숙소에서 쉴 때에도 어~ 같이 오늘 하루 여...
17  SD2000001  어~ 또 함께라면은 또 누가 누구와 가는 것도 굉장히 중요한데 어~ 저는 저랑 잘 ...
18  SD2000001  친구랑 갔을 때에는 일단 친구들만의 통하는 것들이 있기 때문에 함께 이제 좀 더 웃...
19  SD2000001  엄마랑 간다면 아무래도 엄마가 경비적인 측면에서 도움을 주시기 때문에 어~ 쪼금 더...
20  SD2000001  아~ 또 엄마랑 갔을 때는 엄마랑 저랑 입맛이 굉장히 비슷하기 때문에 어~ 특히 해...
21  SD2000001                           혹시 여행 가서 먹는 음식은 어떻게 드세요?
22  SD2000002               저는 여행 가서는 여행지에서의 음식을 먹는 걸 되게 좋아하는데요.
23  SD2000002   저는 유럽에서는 제가 빵을 별로 좋아하지 않아서 서양식 음식을 선호하는 편은 아니에요.
24  SD2000002  그렇지만 유 여행지에 갔으면 거기서 유명한 음식을 한 번쯤은 먹어보는 게 굉장히 좋...
25  SD2000002  어~ 인상 깊었던 음식은 프랑스에서 먹었던 달팽이 요리가 있습니다. 어~ 되게 제가...
26  SD2000002  그리고 베트남이나 이런 입맛이 맞는 여행지에 가면 사실 굳이 한식을 찾을 필요가 없...
27  SD2000002              그럼 그래서 음식을 먹는 데 있어서는 조금 돈을 아끼지 않는 편인데
28  SD2000002  name 씨는 여행을 할 때 절약하는 스타일인지 아니면 돈을 이제 조금 펑펑 쓰더라...
29  SD2000001  아~ 저는 어~ 여행에 가서만큼은 그래도 돈을 아끼지 말고 어~ 많이 쓰면서 여행을...
30  SD2000001  어~ 물론 무한대로 돈을 계속 쓰자라는 거는 아니고 어느 정도 예산을 정해놓고 그 ...
31  SD2000001  어~ 물론 가까운 여행지나 국내 여행지 같은 경우에는 어~ 다시 오기가 쉽기 때문에...
32  SD2000001  어~ 좀 멀리 가거나 해외 특히 해외를 가는 경우에는 다시 방문하기가 쉽지 않은 경...

In [2]:
import json
import pandas as pd


def lambda_preprocess_chat(conv_df:pd.DataFrame)->str:
    result = []
    past_speaker = None
    for _, row in conv_df.iterrows():
        if past_speaker == row['speaker']:
            result += [' ' + row['utterance']]
        else:
            result += [f"\n\n {row['speaker']} : {row['utterance']}"]
            past_speaker = row['speaker']

    xdata = ''.join(result)
    return xdata



with open("./data/일상대화요약_train.json", 'r') as f:
    data = json.load(f)

In [39]:


df = pd.DataFrame(data)
df['subject_keyword'] = df['input'].apply(lambda x: ', '.join(x['subject_keyword']))
df['conversation'] = df['input'].apply(lambda x: x['conversation'])
df['chat_data'] = df['conversation'].apply(lambda x: lambda_preprocess_chat(pd.DataFrame(x)))
df['speaker1'] = df['conversation'].apply(lambda x: pd.DataFrame(x)['speaker'].unique()[0])
df['speaker2'] = df['conversation'].apply(lambda x: pd.DataFrame(x)['speaker'].unique()[1])

In [40]:
message = [
    {'role' : 'system', 'content' : prompt_template.SYSTEM_PROMPT_1},
    {'role' : 'user', 'content' : chat}
]

NameError: name 'prompt_template' is not defined

In [41]:
df

,id,input,output,subject_keyword,conversation,chat_data,speaker1,speaker2
0,nikluge-2024-일상 대화 요약-train-000001,"{'conversation': [{'speaker': 'SD2000001', 'ut...",이 대화에서 화자들은 좋았던 여행지와 기억나는 주요 명소에 대해 이야기했습니다. S...,해외여행,"[{'speaker': 'SD2000001', 'utterance': '저는 여행 ...",\n\n SD2000001 : 저는 여행 다니는 것을 굉장히 좋아하는데요. 그래가지...,SD2000001,SD2000002
1,nikluge-2024-일상 대화 요약-train-000002,"{'conversation': [{'speaker': 'SD2000002', 'ut...","이 대화에서 화자들은 쇼핑하기, 숙소, 음식 등 각자 선호하는 여행 스타일에 대해 ...","여행 스타일, 숙소, 음식","[{'speaker': 'SD2000002', 'utterance': '여행 다닐 ...",\n\n SD2000002 : 여행 다닐 때 저는 쇼핑 같이 물건을 사는 걸 되게 ...,SD2000002,SD2000001
2,nikluge-2024-일상 대화 요약-train-000003,"{'conversation': [{'speaker': 'SD2000001', 'ut...",이 대화에서 화자들은 기억에 남는 여행지와 일화에 대해 이야기했습니다. SD2000...,"여행지, 일화","[{'speaker': 'SD2000001', 'utterance': '어~ 그래서...",\n\n SD2000001 : 어~ 그래서 한번은 여행을 다니다가 준비했던 현금이 ...,SD2000001,SD2000002
3,nikluge-2024-일상 대화 요약-train-000004,"{'conversation': [{'speaker': 'SD2000005', 'ut...",두 화자는 이 대화에서 좋아하는 음식과 싫어하는 음식에 대해 말했습니다. SD200...,"음식, 선호, 길거리 음식, 싫어하는 음식","[{'speaker': 'SD2000005', 'utterance': 'name1 ...",\n\n SD2000005 : name1 씨는 주로 어떤 음식 좋아하시나요?\n\n...,SD2000005,SD2000006
4,nikluge-2024-일상 대화 요약-train-000005,"{'conversation': [{'speaker': 'SD2000006', 'ut...",두 화자는 이 대화에서 다이어트 식품과 좋아하는 음료에 대해 이야기했습니다. SD2...,"다이어트 식품, 마실것","[{'speaker': 'SD2000006', 'utterance': '그러면 na...",\n\n SD2000006 : 그러면 name2 씨는 어~ 다이어트를 하시는진 잘 ...,SD2000006,SD2000005
...,...,...,...,...,...,...,...,...
501,nikluge-2024-일상 대화 요약-train-000502,"{'conversation': [{'speaker': 'SD2100596', 'ut...",두 화자는 이 대화에서 유명 유튜버의 식당 추천과 음식 장사의 성공 요인에 대해서 ...,company-name5,"[{'speaker': 'SD2100596', 'utterance': '그 comp...",\n\n SD2100596 : 그 company-name1이 저번에 구독자 이벤트로...,SD2100596,SD2100595
502,nikluge-2024-일상 대화 요약-train-000503,"{'conversation': [{'speaker': 'SD2100598', 'ut...",이 대화에서 화자들은 주택 마련 방법과 고충에 대해서 이야기했습니다. SD21005...,행복 주택,"[{'speaker': 'SD2100598', 'utterance': '나 이번 달...",\n\n SD2100598 : 나 이번 달 또 적자 났어요.\n\n SD210059...,SD2100598,SD2100597
503,nikluge-2024-일상 대화 요약-train-000504,"{'conversation': [{'speaker': 'SD2100598', 'ut...",이 대화에서 화자들은 현재 소득에서 수익 창출 방법에 대해 이야기 했습니다. SD2...,수익,"[{'speaker': 'SD2100598', 'utterance': '저는 지금 ...",\n\n SD2100598 : 저는 지금 제일 걱정하고 고민하는 게 차를 이제 다시...,SD2100598,SD2100597
504,nikluge-2024-일상 대화 요약-train-000505,"{'conversation': [{'speaker': 'SD2100599', 'ut...",이 대화에서 화자들은 좋아하는 치킨 브랜드와 어제 저녁 먹은 음식과 점심으로 먹은 ...,점심,"[{'speaker': 'SD2100599', 'utterance': '동네에 맛있...",\n\n SD2100599 : 동네에 맛있는 치킨집이 없는 거 같아. 요새 노랑통닭...,SD2100599,SD2100600
505,nikluge-2024-일상 대화 요약-train-000506,"{'conversation': [{'speaker': 'SD2100600', 'ut...",이 대화에서 화자들은 맛집 소개 및 추천에 대해서 이야기했습니다. SD2100600...,맛집,"[{'speaker': 'SD2100600', 'utterance': '집 근처에 ...",\n\n SD2100600 : 집 근처에 그러면 맛집 없어?\n\n SD210059...,SD2100600,SD2100599

In [47]:
from datasets import Dataset, Features, Value, Sequence
from functools import partial
from prompt import prompt_template

aa = Dataset.from_pandas(df)


def tmp(examples):
    prompt = [prompt_template.USER_PROMPT_1(subject,s1,s2) for subject, s1, s2 in zip(examples['subject_keyword'],
                                examples['speaker1'],
                                examples['speaker2'])]
    return prompt
aa.map(tmp)

Map:   0%|          | 0/506 [00:00<?, ? examples/s]

TypeError: Provided `function` which is applied to all elements of table returns a variable of type <class 'list'>. Make sure provided `function` returns a variable of type `dict` (or a pyarrow table) to update the dataset or `None` if you are only interested in side effects.

/home/rainism/anaconda3/envs/LLM/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
data[0]

{'id': 'nikluge-2024-일상 대화 요약-train-000001',
 'input': {'conversation': [{'speaker': 'SD2000001',
    'utterance': '저는 여행 다니는 것을 굉장히 좋아하는데요. 그래가지고 스페인이나 뭐 영국 유럽 아니면 국내에서도 뭐 강릉이나 전주 같은 데를 많이 다녔는데'},
   {'speaker': 'SD2000001', 'utterance': '혹시 여행 다니는 거 좋아하시나요?'},
   {'speaker': 'SD2000002',
    'utterance': '저 여행 다니는 거 되게 좋아해서 대학교 내내 여행을 엄청 많이 다녔었는데요.'},
   {'speaker': 'SD2000002',
    'utterance': '제가 고등학교 때는 여행에 대해 흥미가 없었는데 그게 좀 아버지가 짠대로 패키지처럼 여행을 다녀서 그런 것 같아요.'},
   {'speaker': 'SD2000002',
    'utterance': '그래서 대학교 간 이후로는 해외여행을 되게 많이 갔었는데 그중에서 제일 기 좋았던 거는 스페인이랑 포르투갈이었거든요.'},
   {'speaker': 'SD2000002',
    'utterance': '어~ 혹시 포르투갈이나 스페인 유럽 쪽 다녀오신 적 있으신가요?'},
   {'speaker': 'SD2000001', 'utterance': '어~ 네. 저도 우연히 스페인과 포르투갈을 다녀왔었었습니다.'},
   {'speaker': 'SD2000001',
    'utterance': '어~ 저는 스페인 중에서도 마드리드에 근교에 있었던 톨레도라는 지역이 굉장히 좋았는데요. 그 톨레도에서 특히 기억에 남았던 거는 거기에 대성당이 있는데 그 성당이 엄청 화려하더라고요. 그래서 거기를 꾸며논 거를 보면은 금을 엄청 많이 사용해가지고 되게 빤짝빤짝하고 좀 성당은 보통 좀 소박하다라는 인식이 있었는데 아~ 이렇게 화려한 성당도 있구나라는 거를 새롭게 알게 됐었습니다.'},
   {'speaker': 'SD2000001',
    'utterance': '어~ 또 톨레도에 지역 음식도 같이 먹었었는데 아~ 이름은 지금 잘 생각이 나지는 않지만 굉장히 달달했던 그런 디저트 종류였는데 그~ 디저트도 먹고 그다음에 천천히 걸어 다니면서 주변 풍경도 보고 근교 여행만의 약간 소박한 맛이 있었다고 생각을 합니다.'},
   {'speaker': 'SD2000001',
    'utterance': '어~ 또 물론 마드리드도 굉장히 좋았는데 유럽 여행을 많이 가셨다고 해서 혹시 톨레도도 가본 적이 있나요?'},
   {'speaker': 'SD2000002',
    'utterance': '아~ 제가 톨레도도 다녀왔는데 저는 이제 여행 일정을 길게 잡아서 톨레도는 하루를 봤는데 도 그렇게 너무 더웠기 때문에 많이 보진 못한 것 같아요.'},
   {'speaker': 'SD2000002',
    'utterance': '그때는 버스 관광버스를 타고 계속 돌아다니면서 이제 내리는 데마다 관광을 할 수 있는 버스를 탔는데요. 그 버스를 타고 전체를 다 내려서 보려고 했지만 날씨가 너무 더워서 금방 금방 이제 xx 장소로 넘어갔던 것 같 같습니다.'},
   {'speaker': 'SD2000002',
    'utterance': '거기는 이제 고대 도시라고 해서 사람들이 많이 추천한 거에 비해서는 저는 하루를 잡기에는 조금 부족한 여행지라는 생각이 들었고'},
   {'speaker': 'SD2000002', 'utterance': '오히려 광장에서 쇼핑을 했던 게 더 기억에 남습니다.'}],
  'subject_keyword': ['해외여행']},
 'output': '이 대화에서 화자들은 좋았던 여행지와 기억나는 주요 명소에 대해 이야기했습니다. SD2000001은 여행을 좋아하여 국내, 해외 여행을 많이 다녔다고 말했습니다. 특히 기억에 남는 여행지로 스페인 마드리드의 톨레도를 소개했습니다. 그 중 화려하게 꾸며진 대성당과 디저트가 인상적이었다고 이야기했습니다. SD2000002는 대학교에 진학한 후 해외여행을 자주 다녔고, 스페인과 포루투갈이 가장 기억에 남는 여행지라고 말했습니다. 그리고 톨레도도 다녀왔지만 날씨가 더워서 제대로 구경하지 못했다는 경험을 이야기했습니다.'}

In [7]:
Dataset.from_dict(data)

AttributeError: 'list' object has no attribute 'items'

In [6]:
from prompt import prompt_template
import torch

class CustomDataset(Dataset):
    def __init__(self, data):
        self.IGNORE_INDEX=-100
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        row = self.data[idx]

        return row
        # return input_ids

In [7]:
aa = CustomDataset(data)
aa

AttributeError: property 'data' of 'CustomDataset' object has no setter